GO-1542 Add alpha version assert

diff --git a/.github/actions/check_alpha/action.yml b/.github/actions/check_alpha/action.yml
--- a/.github/actions/check_alpha/action.yml
+++ b/.github/actions/check_alpha/action.yml
@@ -1,38 +1,40 @@
 name: Check Alpha
 
-jobs:
-  check_alpha:
-    steps:
-      - name: Check if tag contains "-alpha"
-        id: check_tag
-        run: |
-          if [[ "$GITHUB_REF" == *"-alpha" ]]; then
-            echo "Tag contains '-alpha'"
-            echo "::set-output name=tag_alpha_found::true"
-          else
-            echo "Tag does not contain '-alpha'"
-            echo "::set-output name=tag_alpha_found::false"
-          fi
+description: 'Check if tag and go.mod in consistency'
 
-      - name: Check go.mod for alpha any-sync
-        id: check_go_mod
-        run: |
-          if grep -qE "github.com/anyproto/any-sync .*-alpha" go.mod; then
-            echo "Required line found in go.mod"
-            echo "::set-output name=anysync_alpha_found::true"
-          else
-            echo "Required line not found in go.mod"
-            echo "::set-output name=anysync_alpha_found::false"
-          fi
+runs:
+  using: "composite"
+  steps:
+    - name: Check if tag contains "-alpha"
+      id: check_tag
+      run: |
+        if [[ "$GITHUB_REF" == *"-alpha" ]]; then
+          echo "Tag contains '-alpha'"
+          echo "tag_alpha_found=true" >> "$GITHUB_OUTPUT"
+        else
+          echo "Tag does not contain '-alpha'"
+          echo "tag_alpha_found=false" >> "$GITHUB_OUTPUT"
+        fi
 
-      - name: Assert either alpha or not
-        run: |
-          if [[ ${{ steps.check_tag.outputs.tag_alpha_found }} == "true" && ${{ steps.check_go_mod.outputs.anysync_alpha_found }} == "false" ]]; then
-            echo "Tag contains '-alpha' but go.mod does not contain 'any-sync' alpha"
-            exit 1
-          elif [[ ${{ steps.check_tag.outputs.tag_alpha_found }} == "false" && ${{ steps.check_go_mod.outputs.anysync_alpha_found }} == "true" ]]; then
-            echo "Tag does not contain '-alpha' but go.mod contains 'any-sync' alpha"
-            exit 1
-          else
-            echo "All good"
-          fi
+    - name: Check go.mod for alpha any-sync
+      id: check_go_mod
+      run: |
+        if grep -qE "github.com/anyproto/any-sync .*-alpha" go.mod; then
+          echo "Required line found in go.mod"
+          echo "anysync_alpha_found=true" >> "$GITHUB_OUTPUT"
+        else
+          echo "Required line not found in go.mod"
+          echo "anysync_alpha_found=false" >> "$GITHUB_OUTPUT"
+        fi
+
+    - name: Assert either alpha or not
+      run: |
+        if [[ ${{ steps.check_tag.outputs.tag_alpha_found }} == "true" && ${{ steps.check_go_mod.outputs.anysync_alpha_found }} == "false" ]]; then
+          echo "Tag contains '-alpha' but go.mod does not contain 'any-sync' alpha"
+          exit 1
+        elif [[ ${{ steps.check_tag.outputs.tag_alpha_found }} == "false" && ${{ steps.check_go_mod.outputs.anysync_alpha_found }} == "true" ]]; then
+          echo "Tag does not contain '-alpha' but go.mod contains 'any-sync' alpha"
+          exit 1
+        else
+          echo "All good"
+        fi
