add logs to ci build

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -79,8 +79,17 @@ jobs:
           echo "addon signature: $ADDON_FILE_SIGNATURE\n"
           [[ $ADDON_FILE_SIGNATURE == "00000000" ]] && echo "INVALID ADDDON FILE SIGNATURE!" && exit 1
           mv clientlibrary/jsaddon/build addon
+          ADDON_FILE_SIGNATURE=`head -c 4 addon/Release/addon.node | xxd -ps -g 4`
+          echo "addon signature2: $ADDON_FILE_SIGNATURE\n"
+          [[ $ADDON_FILE_SIGNATURE == "00000000" ]] && echo "INVALID ADDDON FILE SIGNATURE!" && exit 1
           tar -czvf js_${VERSION}_darwin-amd64.tar.gz protobuf addon
           mv js_${VERSION}_darwin-amd64.tar.gz .release/
+          cd .release
+          tar -xzf js_${VERSION}_darwin-amd64.tar.gz
+          ADDON_FILE_SIGNATURE=`head -c 4 addon/Release/addon.node | xxd -ps -g 4`
+          echo "addon signature3: $ADDON_FILE_SIGNATURE\n"
+          [[ $ADDON_FILE_SIGNATURE == "00000000" ]] && echo "INVALID ADDDON FILE SIGNATURE!" && exit 1
+          cd ..
           rm ./darwin-amd64*
       - name: Upload protobuf artifact for linux build
         uses: actions/upload-artifact@v2
